<!DOCTYPE html><html lang="ja-JP"><head><meta charset="utf-8"><meta name="X-UA-Compatible" content="IE=edge"><meta name="author" content="Core"><title>開発メモ その138 ChainerでDCGANのサンプル実行中に遭遇したエラー · A certain engineer "COMPLEX"</title><meta name="description" content="Introductionchainerに付属している**DCGAN(Deep Convolution Generative Adversarial Networks)**のサンプルを動かした際のエラーについての対応メモ。
Resolutionbackend がない下記のエラーが出る。 [code l"><meta name="keywords" content="极限博客,极限Blog,博客,极限"><meta content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0" name="viewport"><meta content="yes" name="apple-mobile-web-app-capable"><meta content="black" name="apple-mobile-web-app-status-bar-style"><meta content="telephone=no" name="format-detection"><meta name="renderer" content="webkit"><link rel="stylesheet" href="/css/style.css"><link rel="stylesheet" href="/css/blog_basic.css"><link rel="stylesheet" href="/css/font-awesome.min.css"><link rel="alternate" type="application/atom+xml" title="ATOM 1.0" href="/atom.xml"><script src="/js/jquery.js"></script><meta name="generator" content="Hexo 5.1.0"></head><body><div class="sidebar animated fadeInDown"><div class="logo-title"><div class="title"><img src="/images/logo@2x.png" style="width:127px;"><h3 title=""><a href="/">A certain engineer &quot;COMPLEX&quot;</a></h3><div class="description"><p>心之所愿，无事不成。<br> Nothing is impossible to a willing heart.</p></div></div></div><ul class="social-links"><li><a target="_blank" rel="noopener" href="https://github.com/mrcore"><i class="fa fa-github"></i></a></li><li><a href="mailto:x@jixian.io"><i class="fa fa-envelope"></i></a></li><li><a target="_blank" rel="noopener" href="http://sighttp.qq.com/authd?IDKEY="><i class="fa fa-qq"></i></a></li><li><a target="_blank" rel="noopener" href="https://zhihu.com/people/"><i class="fa fa-mortar-board"></i></a></li></ul><div class="footer"><div class="p"> <span>© 2017 - 2020 </span><i class="fa fa-star"></i><span> Core</span></div><div class="by_farbox"><span>Powered by </span><a href="https://hexo.io/" target="_blank">Hexo </a><span> & </span><a href="https://github.com/mrcore/hexo-theme-Anatole-Core" target="_blank">Anatole-Core  </a></div></div></div><div class="main"><div class="page-top animated fadeInDown"><div class="nav"><li><a href="/">ホーム</a></li><li><a href="/archives">アーカイブ</a></li><li><a href="/tags">タグ</a></li><li><a href="/about">自己紹介</a></li><li><a href="/guestbook">メッセージ</a></li></div><div class="information"><div class="back_btn"><li><a class="fa fa-chevron-left" onclick="window.history.go(-1)"> </a></li></div></div></div><div class="autopagerize_page_element"><div class="content"><div class="post-page"><div class="post animated fadeInDown"><div class="post-title"><h3><a>開発メモ その138 ChainerでDCGANのサンプル実行中に遭遇したエラー</a></h3></div><div class="post-content"><h1 id="Introduction"><a href="#Introduction" class="headerlink" title="Introduction"></a>Introduction</h1><p><strong>chainer</strong>に付属している**DCGAN(Deep Convolution Generative Adversarial Networks)**のサンプルを動かした際のエラーについての対応メモ。</p>
<h1 id="Resolution"><a href="#Resolution" class="headerlink" title="Resolution"></a>Resolution</h1><h3 id="backend-がない"><a href="#backend-がない" class="headerlink" title="backend がない"></a>backend がない</h3><p>下記のエラーが出る。 [code lang=”cmd”] &gt;python -i train_dcgan.py Traceback (most recent call last): File “train_dcgan.py”, line 9, in <module> from net import Discriminator File “D:\Works\Python\Envs\chainer\chainer\examples\dcgan\net.py”, line 5, in <module> from chainer import backend ImportError: cannot import name ‘backend’ [/code] 理由としては、現時点(2018/10/21)でのgithubのリポジトリがChainerの<strong>v5.0</strong>へ移行し始めている。 その過程でI/Fに下記の変更がはいった模様。 </p>


<p>要するに、 [code lang=”python”] from chainer import backends [/code] が [code lang=”python”] from chainer import backend [/code] こうなったと。 で、<strong>pip</strong>からインストールしたchainerは [code lang=”cmd”] python -m pip freeze chainer certifi==2018.10.15 chainer==4.5.0 colorama==0.3.9 cupy==4.5.0 fastrlock==0.4 filelock==3.0.9 isort==4.3.4 lazy-object-proxy==1.3.1 mccabe==0.6.1 numpy==1.15.2 protobuf==3.6.1 six==1.11.0 typed-ast==1.1.0 wincertstore==0.2 [/code] となっており、ずれている、というわけです。 なので、githubのブランチを<strong>v4</strong>に変更して実行するのが正解。</p>
<h3 id="PIL-がない"><a href="#PIL-がない" class="headerlink" title="PIL がない"></a>PIL がない</h3><p>[code lang=”cmd”] &gt;python -i train_dcgan.py Traceback (most recent call last): File “train_dcgan.py”, line 14, in <module> from visualize import out_generated_image File “D:\Works\Python\Envs\chainer\chainer\examples\dcgan\visualize.py”, line 6, in <module> from PIL import Image ModuleNotFoundError: No module named ‘PIL [/code] なので、<strong>Pillow</strong>をインストール。 いつも、<strong>PIL</strong>をインストールしようとするけど、そういう名前のパッケージはないのね。 [code lang=”cmd”] &gt;python -m pip install Pillow Collecting Pillow Downloading <a target="_blank" rel="noopener" href="https://files.pythonhosted.org/packages/bd/39/c76eaf781343162bdb1cf4854cb3bd5947a87ee44363e5acd6c48d69c4a1/Pillow-5.3.0-cp36-cp36m-win/_amd64.whl">https://files.pythonhosted.org/packages/bd/39/c76eaf781343162bdb1cf4854cb3bd5947a87ee44363e5acd6c48d69c4a1/Pillow-5.3.0-cp36-cp36m-win\_amd64.whl</a> (1.6MB) 100% |████████████████████████████████| 1.6MB 975kB/s Installing collected packages: Pillow Successfully installed Pillow-5.3.0 [/code]</p>
<h3 id="CUDAが使えない"><a href="#CUDAが使えない" class="headerlink" title="CUDAが使えない"></a>CUDAが使えない</h3><p>[code lang=”cmd”] &gt;python -i train_dcgan.py -g 0 GPU: 0 # Minibatch-size: 50 # n_hidden: 100 # epoch: 1000<br>D:\Works\Python\Envs\chainer\lib\site-packages\chainer\backends\cuda.py:95: UserWarning: cuDNN is not enabled. Please reinstall CuPy after you install cudnn (see <a target="_blank" rel="noopener" href="https://docs-cupy.chainer.org/en/stable/install.html#install-cupy-with-cudnn-and-nccl">https://docs-cupy.chainer.org/en/stable/install.html#install-cupy-with-cudnn-and-nccl</a>). ‘cuDNN is not enabled.\n’ [/code] <strong>cuDNN</strong>をインストールして、<strong>CuPy</strong>を再インストールしろ、ってエラーです。 自分の環境にインストールされているcuDNNを調べて適切なCuPyをインストールします。 普通の<strong>CuPy</strong>は削除しなくてもOKでした。 [code lang=”cmd”] &gt;python -m pip install cupy-cuda92 Collecting cupy-cuda92 Downloading <a target="_blank" rel="noopener" href="https://files.pythonhosted.org/packages/1a/23/0a8f34c97486ff7e18c5db9bcd76f62605adcf9b63f6fc247229e5df24b4/cupy/_cuda92-4.5.0-cp36-cp36m-win/_amd64.whl">https://files.pythonhosted.org/packages/1a/23/0a8f34c97486ff7e18c5db9bcd76f62605adcf9b63f6fc247229e5df24b4/cupy\_cuda92-4.5.0-cp36-cp36m-win\_amd64.whl</a> (231.7MB) 100% |████████████████████████████████| 231.7MB 92kB/s Requirement already satisfied: numpy&gt;=1.9.0 in d:\works\python\envs\chainer\lib\site-packages (from cupy-cuda92) (1.15.2) Requirement already satisfied: six&gt;=1.9.0 in c:\users\takuya\appdata\roaming\python\python36\site-packages (from cupy-cuda92) (1.11.0) Requirement already satisfied: fastrlock&gt;=0.3 in d:\works\python\envs\chainer\lib\site-packages (from cupy-cuda92) (0.4) Installing collected packages: cupy-cuda92 Successfully installed cupy-cuda92-4.5.0 [/code] cuDNNは<strong>C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\vX.X</strong>に適切に展開されている必要があります。</p>
</div><div class="post-footer"><div class="meta"><div class="info"><i class="fa fa-sun-o"></i><span class="date">2018-10-22</span><i class="fa fa-tag"></i><a class="tag" href="/categories/e3-83-87-e3-82-a3-e3-83-bc-e3-83-97-e3-83-a9-e3-83-bc-e3-83-8b-e3-83-b3-e3-82-b0/" title="%e3%83%87%e3%82%a3%e3%83%bc%e3%83%97%e3%83%a9%e3%83%bc%e3%83%8b%e3%83%b3%e3%82%b0">%e3%83%87%e3%82%a3%e3%83%bc%e3%83%97%e3%83%a9%e3%83%bc%e3%83%8b%e3%83%b3%e3%82%b0 </a><a class="tag" href="/categories/e3-83-87-e3-82-a3-e3-83-bc-e3-83-97-e3-83-a9-e3-83-bc-e3-83-8b-e3-83-b3-e3-82-b0/Chainer/" title="Chainer">Chainer </a><a class="tag" href="/categories/ディープラーニング/" title="ディープラーニング">ディープラーニング </a><span class="leancloud_visitors"></span></div></div></div></div><div class="share"><div class="evernote"><a class="fa fa-bookmark" href="" onclick="javascript:join_favorite()" ref="sidebar"></a></div><div class="twitter"><a class="fa fa-twitter" target="_blank" rel="noopener" href="http://twitter.com/home?status=,https://takuya-takeuchi.github.io/2018/10/22/3221/,A certain engineer &quot;COMPLEX&quot;,開発メモ その138 ChainerでDCGANのサンプル実行中に遭遇したエラー,;"></a></div></div><div class="pagination"><ul class="clearfix"><li class="pre pagbuttons"><a class="btn" role="navigation" href="/2018/10/24/1427/" title="ディープラーニング CNTK その6 指紋紋様分類">前へ</a></li><li class="next pagbuttons"><a class="btn" role="navigation" href="/2018/10/20/3218/" title="開発メモ その137 Chainer with CUDA on Anaconda3 for Windowsを使う">次へ</a></li></ul></div></div></div></div></div><script src="/js/jquery-migrate-1.2.1.min.js"></script><script src="/js/jquery.appear.js"></script><script src="/js/add-bookmark.js"></script></body></html>